FROM node:10

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY package*.json ./

RUN npm install
RUN npm install -g git
RUN git config --global user.email "info@token.land"
RUN git config --global user.name "tokenland"
# If you are building your code for production
# RUN npm ci --only=production

COPY . .

CMD [ "npm", "start" ]
