FROM node:10

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY package*.json ./

RUN npm install
RUN npm install -g git
RUN git config --global user.email "slptoken@example.com"
RUN git config --global user.name "slptoken"
# If you are building your code for production
# RUN npm ci --only=production


# Bundle app source
COPY bin/ ./bin/
COPY modules/ ./modules/
COPY public/ ./public/
COPY routes ./routes/
COPY views ./views/
COPY app.js ./
COPY .env ./
COPY .dockerignore ./
COPY Dockerfile ./
RUN mkdir gitrepo

#COPY . .


EXPOSE 3001

CMD [ "node", "./bin/www" ]