version: '3'

services: 
    backend: 
        build: 
            context: ./react-backend
        expose:
            - 3001
        ports: 
            - "3001:3001"

    frontend: 
        build: "./client"
        expose: 
            - 3000
        ports: 
            - "3000:3000"
