version: '3'

services: 
    backend: 
        build: 
            context: ./react-backend
        ports: 
            - "3001:3001"

    frontend: 
        build:
            context: "./client"
        ports: 
            - "3000:3000"
